version: '3.9'

services:
  pdstock_db:
    image: postgres:14.3
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pgadmin
      POSTGRES_DB: pdstock_db
    volumes:
      - pdstockdb_vol:/var/lib/postgresql/data
    networks:
      - pdstock_net

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - pdstock_db
    restart: always
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - pdstockpg_vol:/var/lib/pgadmin
    networks:
      - pdstock_net

  caching_db:
    image: redis
    restart: always
    ports:
      - 5002:6379
    volumes:
      - pdstock_caching_vol:/data
    networks:
      - pdstock_net

volumes:
  pdstockdb_vol:
  pdstockpg_vol:
  pdstock_caching_vol:

networks:
  pdstock_net:
